---
- name: Make sure docker and docker-compose are installed
  hosts: aws_ec2
  become: true
  become_user: root
  tasks:
    - name: Install Docker and Pip
      ansible.builtin.package:
        name: 
          - docker
          - pip
        state: present
        update_cache: true
    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-{{lookup('pipe', 'uname -s')}}-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x 
    - name: Uninstall requests package
      ansible.builtin.yum:
        name: python3-requests-2.25.1-1.amzn2023.0.3.noarch
        state: absent
    - name: Install docker and docker-compose python package
      ansible.builtin.pip:
        name: 
          - docker==6.1.3
          - docker-compose
        state: present